# Beacon configuration.
#
# This requires a gateway with GPS / GNSS.
#
# Please note that the beacon settings are region dependent. The correct
# settings can be found in the LoRaWAN Regional Parameters specification.
[gateway.beacon]

# Compulsory RFU size.
compulsory_rfu_size=2

# Beacon frequency / frequencies (Hz).
frequencies=[
  869525000,
]

# Bandwidth (Hz).
bandwidth=125000

# Spreading factor.
spreading_factor=9

# TX power.
tx_power=14
